
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git laravel zsh-syntax-highlighting zsh-autosuggestions git-flow)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"


# Paths
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH=/usr/local/bin:$PATH
export PATH="$HOME/.local/bin:$PATH"
export XDEBUG_CONFIG="idekey=VSCODE"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# fnm
# export PATH=$HOME/.fnm:$PATH
# eval "`fnm env`"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export EDITOR=nvim
export VISUAL="$EDITOR"


# Aliases

alias avim=/usr/bin/vim
alias vim=nvim

alias x='exit'
alias cls='printf "\33c\e[3J"'

# Filesystem
alias o="open ."
alias s="sublime ."
alias c="code ."
alias p="phpstorm ."

# Laravel/PHP
alias pa='php artisan'
alias atcc='pa cache:clear && pa config:clear'
alias ct='composer test'
alias vtf='vendor/bin/phpunit --colors=always --testdox --filter'
alias at='pa test'
alias atp='pa test --parallel'
alias ats='pa test --stop-on-fail'
alias atf='pa test --filter'
alias tinker="php artisan tinker"

alias ctf='composer test -- --filter'
alias cl='composer lint'
alias cda='composer dump-autoload'
alias clf='composer lint:fix'

# Git
alias nah="git reset --hard && git clean -df"
alias undocommit="git reset HEAD~1"
alias gs="git status"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias galc='git add . && git commit -m'
alias gcap='git commit -am'
alias wip="git commit -am 'wip'"
alias amend="git commit -a --amend"
alias amendn="git commit -a --amend --no-edit"
alias gp='git push'
alias gs='git status'
alias gpcl='git pull && clean_git_branches'
# git new branch
alias gnb='git checkout -b'
# checkout the dev branch, pull changes and remove deleted branches
alias gcdpc='git checkout develop && git pull && clean_git_branches'
# checkout the master branch, pull changes and remove deleted branches
alias gcmpc='git checkout master && git pull && clean_git_branches'
# checkout the mainline branch, pull changes and remove deleted branches
alias gcmlpc='git checkout mainline && git pull && clean_git_branches'
# checkout the staging branch, pull changes and remove deleted branches
alias gcspc='git checkout staging && git pull && clean_git_branches'

# clear the console
alias rs='reset'
# clear the console and return to home
alias rc='reset_console'

# command to update kitty terminal. PS: Same command is used for installing kitty terminal
alias update_kitty='curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin'

# test func
# prints the input
function output_input() {
  echo "Your input: " $1
}

# resets the console
function reset_console() {
  cd && reset
}

# converts and saves youtube video to mp3
function convert_to_mp3() {
  # PS: You must install youtube-dl and ffmpeg library first if you don’t have it.
  youtube-dl --extract-audio --audio-format mp3 -f bestaudio $1
}

# Downloads the videos in a playlist
function download_playlist() {
  youtube-dl -i --yes-playlist -f mp4 $1
}

# Downloads and embed subtitles to a video
function download_with_sub() {
  youtube-dl --write-auto-sub $1
}

# removes local branches deleted from origin, syncs the git branches
function clean_git_branches() {
  git fetch -p && for branch in $(git branch -vv | gawk '{print $1,$4}' | grep 'gone]' | gawk '{print $1}'); do git branch -D $branch; done
}

# restarts ubuntu sound process
function restart_ubuntu_sound() {
  pulseaudio -k && sudo alsa force-reload
}

# switching php versions
function switch_2_php8.1() {
  brew unlink php@7.4
  brew link php@8.1
}

function switch_2_php7.4() {
  brew unlink php@8.1
  brew link php@7.4
}

# Herd injected PHP binary.
export PATH="/Users/geneowak/Library/Application Support/Herd/bin/":$PATH

# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/geneowak/Library/Application Support/Herd/config/php/82/"

# Herd injected PHP 8.1 configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/geneowak/Library/Application Support/Herd/config/php/81/"
